<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateAdvocateBulkUploadsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('advocate_bulk_uploads', function (Blueprint $table) {
            $table->increments('id');
            $table->string('first', 255)->nullable();
            $table->string('last', 255)->nullable();
            $table->string('email', 255)->nullable();
            $table->tinyInteger('registered')->nullable();
            $table->string('level', 255)->nullable();
            $table->string('group_segmentation', 255)->nullable();
            $table->unsignedInteger('user_id_uploader');
            $table->timestamps();
            $table->softDeletes();
        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('advocate_bulk_uploads');
    }
}
