<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateAdvocateProfilesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('advocate_profiles', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('advocate_bulk_upload_id')->nullable();
            $table->unsignedInteger('points')->nullable();
            $table->string('social_accounts', 255)->nullable();
            $table->unsignedInteger('level')->nullable();
            $table->string('email', 255)->nullable();
            $table->string('first', 255)->nullable();
            $table->string('last', 255)->nullable();
            $table->timestamps();
            $table->softDeletes();
        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('advocate_profile');
    }
}
