<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateAdvocateLevelsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('advocate_levels', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('level')->nullable();
            $table->string('level_range', 255)->nullable();
            $table->string('multiplier', 255)->nullable();
            $table->timestamps();
            $table->softDeletes();
        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('advocate_levels');
    }
}
